// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8kHDYZXM1db73XuTt_owdTod-TT9RE4',
    appId: '1:995864520077:android:4817026ae45a242a61c9c4',
    messagingSenderId: '995864520077',
    projectId: 'r-store-6ee75',
    storageBucket: 'r-store-6ee75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZMSq_PcnwIsDlJBHn_Ul2IeQovltJ40',
    appId: '1:995864520077:ios:f2abc7935c0a5bdd61c9c4',
    messagingSenderId: '995864520077',
    projectId: 'r-store-6ee75',
    storageBucket: 'r-store-6ee75.appspot.com',
    androidClientId: '995864520077-23kev7p2o094bae5oe61qiais7qtgf9u.apps.googleusercontent.com',
    iosClientId: '995864520077-rbp1r6lm0uf0r7ardmu43gmccb0t5khd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopxDashboard',
  );
}
